name: train-tracker-env
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - bokeh=1.4.0=py37_0
  - ca-certificates=2019.10.16=0
  - certifi=2019.9.11=py37_0
  - freetype=2.9.1=ha9979f8_1
  - icc_rt=2019.0.0=h0cc432a_1
  - intel-openmp=2019.4=245
  - jinja2=2.10.3=py_0
  - jpeg=9b=hb83a4c4_2
  - libpng=1.6.37=h2a8f88b_0
  - libtiff=4.1.0=h56a325e_0
  - markupsafe=1.1.1=py37he774522_0
  - mkl=2019.4=245
  - mkl-service=2.3.0=py37hb782905_0
  - mkl_fft=1.0.15=py37h14836fe_0
  - mkl_random=1.1.0=py37h675688f_0
  - numpy=1.17.3=py37h4ceb530_0
  - numpy-base=1.17.3=py37hc3f5095_0
  - olefile=0.46=py37_0
  - openssl=1.1.1d=he774522_3
  - packaging=19.2=py_0
  - pillow=6.2.1=py37hdc69c19_0
  - pip=19.3.1=py37_0
  - pyparsing=2.4.4=py_0
  - python=3.7.5=h8c8aaf0_0
  - python-dateutil=2.8.1=py_0
  - pyyaml=5.1.2=py37he774522_0
  - setuptools=41.6.0=py37_0
  - six=1.13.0=py37_0
  - sqlite=3.30.1=he774522_0
  - tk=8.6.8=hfa6e2cd_0
  - tornado=6.0.3=py37he774522_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_0
  - wheel=0.33.6=py37_0
  - wincertstore=0.2=py37_0
  - xz=5.2.4=h2fa13f4_4
  - yaml=0.1.7=hc54c509_2
  - zlib=1.2.11=h62dcd97_3
  - zstd=1.3.7=h508b16e_0
